/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LinkedinRouteImport } from './routes/linkedin'
import { Route as InspoRouteImport } from './routes/inspo'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AnimationsRouteImport } from './routes/animations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsesIndexRouteImport } from './routes/uses/index'
import { Route as MyImageAssetsIndexRouteImport } from './routes/my-image-assets/index'
import { Route as DesignsIndexRouteImport } from './routes/designs/index'
import { Route as CvIndexRouteImport } from './routes/cv/index'

const LinkedinRoute = LinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const InspoRoute = InspoRouteImport.update({
  id: '/inspo',
  path: '/inspo',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimationsRoute = AnimationsRouteImport.update({
  id: '/animations',
  path: '/animations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsesIndexRoute = UsesIndexRouteImport.update({
  id: '/uses/',
  path: '/uses/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyImageAssetsIndexRoute = MyImageAssetsIndexRouteImport.update({
  id: '/my-image-assets/',
  path: '/my-image-assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsIndexRoute = DesignsIndexRouteImport.update({
  id: '/designs/',
  path: '/designs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvIndexRoute = CvIndexRouteImport.update({
  id: '/cv/',
  path: '/cv/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animations': typeof AnimationsRoute
  '/design-system': typeof DesignSystemRoute
  '/inspo': typeof InspoRoute
  '/linkedin': typeof LinkedinRoute
  '/cv/': typeof CvIndexRoute
  '/designs/': typeof DesignsIndexRoute
  '/my-image-assets/': typeof MyImageAssetsIndexRoute
  '/uses/': typeof UsesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animations': typeof AnimationsRoute
  '/design-system': typeof DesignSystemRoute
  '/inspo': typeof InspoRoute
  '/linkedin': typeof LinkedinRoute
  '/cv': typeof CvIndexRoute
  '/designs': typeof DesignsIndexRoute
  '/my-image-assets': typeof MyImageAssetsIndexRoute
  '/uses': typeof UsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animations': typeof AnimationsRoute
  '/design-system': typeof DesignSystemRoute
  '/inspo': typeof InspoRoute
  '/linkedin': typeof LinkedinRoute
  '/cv/': typeof CvIndexRoute
  '/designs/': typeof DesignsIndexRoute
  '/my-image-assets/': typeof MyImageAssetsIndexRoute
  '/uses/': typeof UsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animations'
    | '/design-system'
    | '/inspo'
    | '/linkedin'
    | '/cv/'
    | '/designs/'
    | '/my-image-assets/'
    | '/uses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/animations'
    | '/design-system'
    | '/inspo'
    | '/linkedin'
    | '/cv'
    | '/designs'
    | '/my-image-assets'
    | '/uses'
  id:
    | '__root__'
    | '/'
    | '/animations'
    | '/design-system'
    | '/inspo'
    | '/linkedin'
    | '/cv/'
    | '/designs/'
    | '/my-image-assets/'
    | '/uses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimationsRoute: typeof AnimationsRoute
  DesignSystemRoute: typeof DesignSystemRoute
  InspoRoute: typeof InspoRoute
  LinkedinRoute: typeof LinkedinRoute
  CvIndexRoute: typeof CvIndexRoute
  DesignsIndexRoute: typeof DesignsIndexRoute
  MyImageAssetsIndexRoute: typeof MyImageAssetsIndexRoute
  UsesIndexRoute: typeof UsesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/linkedin': {
      id: '/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof LinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspo': {
      id: '/inspo'
      path: '/inspo'
      fullPath: '/inspo'
      preLoaderRoute: typeof InspoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animations': {
      id: '/animations'
      path: '/animations'
      fullPath: '/animations'
      preLoaderRoute: typeof AnimationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uses/': {
      id: '/uses/'
      path: '/uses'
      fullPath: '/uses/'
      preLoaderRoute: typeof UsesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-image-assets/': {
      id: '/my-image-assets/'
      path: '/my-image-assets'
      fullPath: '/my-image-assets/'
      preLoaderRoute: typeof MyImageAssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/': {
      id: '/designs/'
      path: '/designs'
      fullPath: '/designs/'
      preLoaderRoute: typeof DesignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/': {
      id: '/cv/'
      path: '/cv'
      fullPath: '/cv/'
      preLoaderRoute: typeof CvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimationsRoute: AnimationsRoute,
  DesignSystemRoute: DesignSystemRoute,
  InspoRoute: InspoRoute,
  LinkedinRoute: LinkedinRoute,
  CvIndexRoute: CvIndexRoute,
  DesignsIndexRoute: DesignsIndexRoute,
  MyImageAssetsIndexRoute: MyImageAssetsIndexRoute,
  UsesIndexRoute: UsesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
