/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as MyImageAssetsRouteImport } from './routes/my-image-assets'
import { Route as LinkedinRouteImport } from './routes/linkedin'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as CvRouteImport } from './routes/cv'
import { Route as AnimationsRouteImport } from './routes/animations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignsIndexRouteImport } from './routes/designs/index'
import { Route as Designs12RouteImport } from './routes/designs/12'

const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const MyImageAssetsRoute = MyImageAssetsRouteImport.update({
  id: '/my-image-assets',
  path: '/my-image-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinRoute = LinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimationsRoute = AnimationsRouteImport.update({
  id: '/animations',
  path: '/animations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsIndexRoute = DesignsIndexRouteImport.update({
  id: '/designs/',
  path: '/designs/',
  getParentRoute: () => rootRouteImport,
} as any)
const Designs12Route = Designs12RouteImport.update({
  id: '/designs/12',
  path: '/designs/12',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animations': typeof AnimationsRoute
  '/cv': typeof CvRoute
  '/design-system': typeof DesignSystemRoute
  '/linkedin': typeof LinkedinRoute
  '/my-image-assets': typeof MyImageAssetsRoute
  '/uses': typeof UsesRoute
  '/designs/12': typeof Designs12Route
  '/designs/': typeof DesignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animations': typeof AnimationsRoute
  '/cv': typeof CvRoute
  '/design-system': typeof DesignSystemRoute
  '/linkedin': typeof LinkedinRoute
  '/my-image-assets': typeof MyImageAssetsRoute
  '/uses': typeof UsesRoute
  '/designs/12': typeof Designs12Route
  '/designs': typeof DesignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animations': typeof AnimationsRoute
  '/cv': typeof CvRoute
  '/design-system': typeof DesignSystemRoute
  '/linkedin': typeof LinkedinRoute
  '/my-image-assets': typeof MyImageAssetsRoute
  '/uses': typeof UsesRoute
  '/designs/12': typeof Designs12Route
  '/designs/': typeof DesignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animations'
    | '/cv'
    | '/design-system'
    | '/linkedin'
    | '/my-image-assets'
    | '/uses'
    | '/designs/12'
    | '/designs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/animations'
    | '/cv'
    | '/design-system'
    | '/linkedin'
    | '/my-image-assets'
    | '/uses'
    | '/designs/12'
    | '/designs'
  id:
    | '__root__'
    | '/'
    | '/animations'
    | '/cv'
    | '/design-system'
    | '/linkedin'
    | '/my-image-assets'
    | '/uses'
    | '/designs/12'
    | '/designs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimationsRoute: typeof AnimationsRoute
  CvRoute: typeof CvRoute
  DesignSystemRoute: typeof DesignSystemRoute
  LinkedinRoute: typeof LinkedinRoute
  MyImageAssetsRoute: typeof MyImageAssetsRoute
  UsesRoute: typeof UsesRoute
  Designs12Route: typeof Designs12Route
  DesignsIndexRoute: typeof DesignsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-image-assets': {
      id: '/my-image-assets'
      path: '/my-image-assets'
      fullPath: '/my-image-assets'
      preLoaderRoute: typeof MyImageAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin': {
      id: '/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof LinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animations': {
      id: '/animations'
      path: '/animations'
      fullPath: '/animations'
      preLoaderRoute: typeof AnimationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/': {
      id: '/designs/'
      path: '/designs'
      fullPath: '/designs/'
      preLoaderRoute: typeof DesignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/12': {
      id: '/designs/12'
      path: '/designs/12'
      fullPath: '/designs/12'
      preLoaderRoute: typeof Designs12RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimationsRoute: AnimationsRoute,
  CvRoute: CvRoute,
  DesignSystemRoute: DesignSystemRoute,
  LinkedinRoute: LinkedinRoute,
  MyImageAssetsRoute: MyImageAssetsRoute,
  UsesRoute: UsesRoute,
  Designs12Route: Designs12Route,
  DesignsIndexRoute: DesignsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
